"""Internal graph interface; business logic depends only on this protocol."""

from typing import Protocol
from uuid import UUID

from memesis.domain.schemas import (
    Assertion,
    CanonicalNode,
    Document,
    DocumentVersion,
    EntityAlias,
    EntityExternalIdentifier,
    Evidence,
    EvidenceSpan,
    GraphEdge,
    MergeDecision,
    NormalizedDocument,
    ScoreRecord,
    Source,
    SourcePolicy,
)


class GraphRepository(Protocol):
    def add_source(self, source: Source) -> Source: ...

    def add_source_policy(self, policy: SourcePolicy) -> SourcePolicy: ...

    def add_document(self, document: Document) -> Document: ...

    def add_document_version(self, version: DocumentVersion) -> DocumentVersion: ...

    def add_evidence(self, evidence: Evidence) -> Evidence: ...

    def get_evidence(self, evidence_id: UUID) -> Evidence | None: ...

    def list_evidence(self, limit: int | None = None) -> list[Evidence]: ...

    def get_normalized_document_for_version(
        self, document_version_id: UUID
    ) -> NormalizedDocument | None: ...

    def get_active_source_policy(self, source_id: UUID) -> SourcePolicy | None: ...

    def find_document_version_by_hash(self, content_hash: str) -> DocumentVersion | None: ...

    def find_evidence_by_hash(self, content_hash: str) -> Evidence | None: ...

    def get_collection_cursor(self, source_id: UUID, boundary_key: str) -> str | None: ...

    def save_collection_cursor(
        self, source_id: UUID, boundary_key: str, cursor: str | None, metadata: dict[str, object]
    ) -> None: ...

    def get_fetch_cache(self, cache_key: str) -> dict[str, object] | None: ...

    def save_fetch_cache(
        self,
        cache_key: str,
        *,
        status_code: int,
        body: str,
        headers: dict[str, object],
        fetched_at: object,
        expires_at: object,
    ) -> None: ...

    def start_collection_run(self, source_id: UUID, query: str) -> UUID: ...

    def finish_collection_run(
        self,
        run_id: UUID,
        *,
        status: str,
        metrics: dict[str, object],
        errors: list[dict[str, object]],
    ) -> None: ...

    def storage_metrics(self) -> dict[str, int]: ...

    def get_extraction_cache(self, cache_key: str) -> dict[str, object] | None: ...

    def save_extraction_cache(self, cache_key: str, record: dict[str, object]) -> None: ...

    def has_evidence_projection(self, evidence_id: UUID, cache_key: str) -> bool: ...

    def save_evidence_projection(self, evidence_id: UUID, cache_key: str) -> None: ...

    def get_decision_cache(self, cache_key: str) -> dict[str, object] | None: ...

    def save_decision_cache(self, cache_key: str, record: dict[str, object]) -> None: ...

    def save_reasoning_run(self, run_id: UUID, record: dict[str, object]) -> None: ...

    def get_reasoning_run(self, run_id: UUID) -> dict[str, object] | None: ...

    def list_reasoning_runs(self, limit: int | None = None) -> list[dict[str, object]]: ...


    def add_entity_alias(self, alias: EntityAlias) -> EntityAlias: ...

    def add_external_identifier(
        self, identifier: EntityExternalIdentifier
    ) -> EntityExternalIdentifier: ...

    def find_node_by_external_identifier(
        self, identifier_type: str, normalized_value: str
    ) -> CanonicalNode | None: ...

    def find_nodes_by_alias(
        self, normalized_alias: str, node_type: str | None = None
    ) -> list[CanonicalNode]: ...

    def find_node_by_identifier_value(self, identifier_type: str, value: str) -> CanonicalNode | None: ...

    def list_nodes(self) -> list[CanonicalNode]: ...

    def list_edges(self) -> list[GraphEdge]: ...

    def get_evidence_span(self, span_id: UUID) -> EvidenceSpan | None: ...

    def get_assertion(self, assertion_id: UUID) -> Assertion | None: ...

    def add_score(self, score: ScoreRecord) -> ScoreRecord: ...

    def get_score(self, score_id: UUID) -> ScoreRecord | None: ...

    def list_scores(
        self, score_type: str | None = None, subject_id: UUID | None = None
    ) -> list[ScoreRecord]: ...

    def add_normalized_document(self, document: NormalizedDocument) -> NormalizedDocument: ...

    def add_evidence_span(self, span: EvidenceSpan) -> EvidenceSpan: ...

    def add_assertion(self, assertion: Assertion) -> Assertion: ...

    def review_assertion(self, assertion_id: UUID, review_state: str) -> Assertion: ...

    def list_active_assertions(self, subject_id: UUID | None = None) -> list[Assertion]: ...

    def list_memory_assertions(self, review_state: str | None = None) -> list[Assertion]: ...

    def review_memory_assertion(self, assertion_id: UUID, state: str, reviewer: str, note: str) -> Assertion: ...

    def add_merge_decision(self, decision: MergeDecision) -> MergeDecision: ...

    def add_tombstone(self, record_type: str, record_id: UUID, reason: str) -> None: ...

    def add_node(self, node: CanonicalNode) -> CanonicalNode: ...

    def get_node(self, node_id: UUID) -> CanonicalNode | None: ...

    def update_node(self, node: CanonicalNode) -> CanonicalNode: ...

    def add_edge(self, edge: GraphEdge) -> GraphEdge: ...

    def get_edge(self, edge_id: UUID) -> GraphEdge | None: ...

    def update_edge(self, edge: GraphEdge) -> GraphEdge: ...

    def delete_edge(self, edge_id: UUID) -> bool: ...

    def delete_node(self, node_id: UUID) -> bool: ...

    def retrieve_subgraph(self, seed_ids: list[UUID], max_hops: int = 2) -> dict[str, object]: ...

    def health(self) -> dict[str, object]: ...
